#!/bin/sh

test -z "$SRC"
if [ "$?" -eq 0 ]; then
  printf 'SRC env var was not set, exiting\n'
  exit 1
fi

if [ $# -eq 0 ]; then
  cd "$SRC"
  return;
fi

srcdir="$SRC/$1"

if [ -d "$srcdir" ]; then
  cd "$srcdir"
fi
