#!/usr/bin/env bash
# NOTE: this script needs to be a zsh function, because you can't cd from a
# script in the bin folder. Those are run in separate processes.

test -z "$SRC"
if [ "$?" -eq 0 ]; then
  echo -e "\033[31mERROR:\033[0m \$SRC env var was not set"
  return
fi

if [ $# -eq 0 ]; then
  cd "$SRC" || exit
  return;
fi

srcdir="$SRC/$1"

if [ -d "$srcdir" ]; then
  cd "$srcdir" || exit
else
  echo -e "\033[31mERROR:\033[0m No directory \"$1\""
fi
