#!/bin/bash

test -z "$SRC"
if [ "$?" -eq 0 ]; then
  echo "\$SRC env var was not set, exiting\n"
  exit 1
fi

if [ $# -eq 0 ]; then
  cd "$SRC" || exit
  return;
fi

srcdir="$SRC/$1"

if [ -d "$srcdir" ]; then
  cd "$srcdir" || exit
fi
