#!/usr/bin/env bash

set -e

APP_PATH="/Applications/iTerm.app"
ICON_URL="https://rosszurowski-assets.s3.amazonaws.com/dotfiles/terminal.app.icns"
ICON_DESTINATION="$HOME/Downloads/$(basename $ICON_URL)"

# Update iTerm's icon to use app icns icon
echo "> Downloading $(basename $ICON_URL)..."
wget -q $ICON_URL -O "$ICON_DESTINATION"

sudo set-icon "$APP_PATH" "$ICON_DESTINATION"
trash "$ICON_PATH"
echo ""
echo "> Done!"
