#!/usr/bin/env bash

set -e

APP_NAME="Obsidian.app"
APP_PATH="/Applications/$APP_NAME"
ICON_URL="https://rosszurowski-assets.s3.amazonaws.com/dotfiles/obsidian.app.icns"
ICON_DESTINATION="$APP_PATH/Contents/Resources/Obsidian.icns"

echo "> Backing up old icon..."
cp "$ICON_DESTINATION" "$ICON_DESTINATION.bak"

# Update iTerm's icon to use app icns icon
echo "> Downloading $(basename $ICON_URL)..."
wget -q $ICON_URL -O $ICON_DESTINATION

echo "> Replacing icon..."
/usr/bin/python - "$ICON_DESTINATION" "$APP_PATH" <<'EOF' || return
import Cocoa
import sys
Cocoa.NSWorkspace.sharedWorkspace().setIcon_forFile_options_(Cocoa.NSImage.alloc().initWithContentsOfFile_(sys.argv[1].decode('utf-8')), sys.argv[2].decode('utf-8'), 0)
EOF

echo "> Clearing icon cache..."
touch "$APP_PATH"
killall Dock
killall Finder

echo "> Done!"
