#!/usr/bin/env bash

DOTFILES_ROOT=$(pwd)

set -e
echo ''

fail () {
  printf "%s\n" "$1" && exit
}

link_files () {
  ln -s "$1" "$2"
  echo "> Linked $1 to $2"
}

install_dotfiles () {
  echo '> Installing dotfiles...'

  symlinks=$(find "$DOTFILES_ROOT" -maxdepth 2 -name \*.symlink)

  overwrite_all=false
  backup_all=false
  skip_all=false

  for source in $symlinks; do
    dest="$HOME/.$(basename ${source%.*})"

    if [ -f "$dest" ] || [ -d "$dest" ]
    then

      overwrite=false
      backup=false
      skip=false

      if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
      then
        echo "> File already exists: $(basename "$source"),"
        echo "> What do you want to do?"
        echo ""
        echo "  [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -rn 1 action

        case "$action" in
          o ) overwrite=true;;
          O ) overwrite_all=true;;
          b ) backup=true;;
          B ) backup_all=true;;
          s ) skip=true;;
          S ) skip_all=true;;
          * ) ;;
        esac
      fi

      if [ "$overwrite" == "true" ] || [ "$overwrite_all" == "true" ]; then
        rm -rf "$dest"
        echo "> Removed $dest"
      fi

      if [ "$backup" == "true" ] || [ "$backup_all" == "true" ]; then
        mv "$dest" "$dest"\.backup
        echo "> Moved $dest to $dest.backup"
      fi

      if [ "$skip" == "false" ] && [ "$skip_all" == "false" ]; then
        link_files "$source" "$dest"
      else
        echo "> Skipping $source..."
      fi
    else
      link_files "$source" "$dest"
    fi
  done

  link_files "$DOTFILES_ROOT/fish" "$HOME/.config/fish/"
}

install_dotfiles
echo ""
echo "> Done!"
