#!/usr/bin/env bash

# I use GPG for signing git commits. This is the setup script for configuring
# it for the first time. `gnupg` is the main utility, and `keychain` and
# `pinentry-mac` let you add your passphrase to the macOS Keychain so you don't
# need to type it in every time.

echo "> Generating GPG key..."
brew install gnupg keychain pinentry-mac
echo "pinentry-program \"$(brew --prefix)/bin/pinentry-mac\"" | tee ~/.gnupg/gpg-agent.conf
# Generate a 4096 bit key
# gpg --full-generate-key
# gpg --list-secret-keys --keyid-format=long

# Copy the part after 'sec rsa4096/<id>' and paste it into your gitconfig
# under the [user.signingkey] section.
open ~/.gitconfig
